package com.example.urlshortener.audit.entity;

public enum AuditAction {
    URL_CREATED,
    URL_DESTINATION_CHANGED,
    URL_EXPIRATION_CHANGED,
    URL_ENABLED,
    URL_DISABLED,
    URL_DELETED,
    URL_BLOCKED,
    URL_UNBLOCKED,
    URL_CAMPAIGN_CHANGED,
    URL_TAGS_CHANGED,
    CAMPAIGN_CREATED,
    CAMPAIGN_UPDATED,
    CAMPAIGN_DELETED,
    API_KEY_CREATED,
    API_KEY_REVOKED,
    WORKSPACE_CREATED,
    WORKSPACE_MEMBER_ADDED,
    WORKSPACE_MEMBER_ROLE_CHANGED,
    WORKSPACE_MEMBER_REMOVED
}
