spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/shortener
    username: shortener
    password: shortener
  data:
    redis:
      host: localhost
      port: 6379
app:
  auth:
    secure-cookies: false
  analytics:
    ip-hash-pepper: local-development-only-change-me
